######################################################################
#  Project
######################################################################

BINARY		= main
SRCFILES	= main.c
LDSCRIPT    = stm32f103c8t6.ld

all: elf bin

include ../Makefile.incl

# End
